### ISSUE TITLE
Could you add tag "openbb" to project?

### ISSUE THREAD

**Issue by DidierRLopes** [kulbinderdio/streamlit_openBB#1]
I am trying to compile all OpenBB open source projects that our community have put together in the same place.

https://github.com/search?q=topic:openbb&type=Repositories&l=&l=

![image](https://user-images.githubusercontent.com/25267873/214743805-7488cc41-cbce-44a7-b929-de1b6558ca21.png)

**Comment by kulbinderdio** [comment]
will do as soon as I figure out how to

**Comment by kulbinderdio** [comment]
done

**Comment by DidierRLopes** [comment]
<img width="1529" alt="Screen Shot 2023-01-30 at 9 17 59 AM" src="https://user-images.githubusercontent.com/25267873/215547981-11a54de9-d03b-455d-8697-9bb04680091b.png">

https://openbb.co/open

**Comment by kulbinderdio** [comment]
cool
